#The file is google PHP App Engine application configuration

application: toknot-php
version: 1
runtime: php
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg))
  static_files: demos/Shop/WebRoot/static/\1
  upload: demos/Shop/WebRoot/upload/(.*\.(gif|png|jpg))

- url: /.*
  script: demos/Shop/WebRoot/index.php